[package]
name = "retris"
version = "0.1.0"
authors = ["DawnMagnet <axccjqh@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch="*"
[build-dependencies]